sudo: required
services: 
  - docker

before_install:
  - docker build -t glenariff555/docker-course-frontend -f Dockerfile.dev .
  

script:
  - docker run glenariff555/docker-course-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-101944250416"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"  

