sudo: required
services: 
  - docker

before_install:
  - docker build -t glenariff555/docker-course-frontend -f Dockerfile.dev .
  



script:
  - docker run glenariff555/docker-course-frontend npm run test -- --coverage