version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
      args:
        - http_proxy
        - https_proxy
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
      args:
        - http_proxy
        - https_proxy
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
